[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "crimson,-code-extractor,"
version = "0.1.0"
description = "From source code, extract useful information.,"
readme = "README.md"
authors = [
  { name="StudyTool", email="None" },
]

classifiers = [
    "Programming Language :: Python :: 3",

    "Intended Audience :: Developers",
    "Topic :: Software Development :: Build Tools",

    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pydantic",
]
requires-python = ">=3.9"

[tool.setuptools.entry-points.console_scripts]
hello = "crimson,-code-extractor,.code-extractor,:main"

[project.urls]
"Homepage" = "https://github.com/None/code-extractor,"
"Bug Tracker" = "https://github.com/None/code-extractor,/issues"
"Discussion" = "https://github.com/None/code-extractor,/discussions"
